apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-manager
  namespace: slic-web-app
  labels:
    app: secret-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-manager
  template:
    metadata:
      labels:
        app: secret-manager
    spec:
      containers:
      - name: secret-manager-container
        image: alfonsomg11/secret-manager:v3
        imagePullPolicy: Always
        command: ['sh', '-c', "sleep 3600"]
      initContainers:
      - name: secret-manager-container-init
        image: alfonsomg11/secret-manager:v3
        imagePullPolicy: Always
        command: ['sh', '-c', "./secrets.sh"]
        env:
        - name: GKE_CLUSTER
          value: "prod"

        - name: SET_ENV_VARS_FOR_SLIC_WEB_APP
          value: "true"

        - name: DEPLOYMENT_NAME_WEB_APP
          value: "test"

        - name: NAMESPACE_WEB_APP
          value: "testing-sm"

        - name: SET_ENV_VARS_FOR_SLIC_API
          value: "true"

        - name: DEPLOYMENT_NAME_API
          value: "test"

        - name: NAMESPACE_API
          value: "testing-sm"
      serviceAccountName: secret-manager